version: '3.7'

volumes:
  postgres:

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=test_messaging
      - POSTGRES_USER=user_messaging
      - POSTGRES_PASSWORD=e5YGE3cQ2ysqHesT
    volumes:
      - postgres:/var/lib/postgresql
      - postgres:/var/log/postgresql
    ports:
      - "5432:5432"

  redis:
    image: redislabs/redisearch
    ports:
      - '6379:6378'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  localstack:
    container_name: localstack
    image: localstack/localstack-light:0.14.0
    environment:
      HOSTNAME_EXTERNAL: localstack
      SERVICES: "sns,sqs,s3"

  messaging-transport-service:
    image: messaging-transport
    ports:
      - "9840:9840"
    environment:
      NAMESPACE: messaging-transport-service-test
      NODE_ENV: development
      SERVER_PORT: 9840
      PUBNUB_PUBLISH_KEY: 'pub-c-5cffb7ac-5697-44e4-bfc4-dcad6bfae55d'
      PUBNUB_SUBSCRIBE_KEY: 'sub-c-c8ad602c-7c09-11e9-81d5-56c3556875f9'
      AWS_REGION: 'us-east-1'
      SQS_ENDPOINT: 'http://localstack:4566'
      SNS_ENDPOINT: 'http://localstack:4566'
      JWT_PUBLIC_KEY: 'sigsecret'
      JWT_ISSUER: 'https://iss.uer'
      AWS_SECRET_ACCESS_KEY: 'invalid'
      AWS_ACCESS_KEY_ID: 'invalid'
      DISABLE_DDTRACE: 1

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    command: --sql_mode=NO_ENGINE_SUBSTITUTION
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_keystoreservice
      MYSQL_USER: root
      MYSQL_PASSWORD: test

  keystore:
    image: keystore
    depends_on:
      - mysql
    environment:
      AWS_ACCESS_KEY_ID: invalid
      AWS_BUCKET_NAME: dev-bucket
      AWS_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: invalid
      AZURE_CLIENT_ID: 89b42340-ea89-47d4-b29c-0ea03236482d
      AZURE_CLIENT_SECRET: -o_uWZ186Q-m_hXb7Dk7Mj2MKv9n8D03r4
      AZURE_KEY_VAULT_NAME: gid-dev-groups-vault
      AZURE_TENANT_ID: 07e42d9d-9529-4908-b3dc-755c9ddae079
      DATABASE_CONNECTION_URL: mysql://root:test@mysql:3306/test_keystoreservice
      DEFAULT_REGION: eu-west-1
      DISABLE_DDTRACE: 1
      JWT_ISSUER: https://iss.uer
      JWT_PUBLIC_KEY: sigsecret
      NAMESPACE: dev
      NODE_ENV: development
      SNS_ENDPOINT: http://localstack:4566
      SQS_ENDPOINT: http://localstack:4566
      SVC_URL_CONSENT: http://consent-service:9502

  contacts:
    image: contacts
    environment:
      NAMESPACE: core
      NODE_ENV: development
      HOSTNAME: http://localhost:9836
      DATABASE_CONNECTION_URL: postgres://contacts:blanks@postgres:5432/contacts?debug=false&charset=utf8
      OBFUSCATED_SALT: a_nice_testing_salty
      AWS_REGION: 'us-east-1'
      SQS_ENDPOINT: 'http://localstack:4566'
      SNS_ENDPOINT: 'http://localstack:4566'
      JWT_PUBLIC_KEY: 'sigsecret'
      JWT_ISSUER: 'https://iss.uer'
      AWS_SECRET_ACCESS_KEY: 'invalid'
      AWS_ACCESS_KEY_ID: 'invalid'
      DISABLE_DDTRACE: 1

  messaging-service:
    image: messaging-legacy-core
    ports:
      - "9836:9836"
    depends_on:
      - postgres
      - redis
      - localstack
    environment:
      NAMESPACE: messaging-service-test
      NODE_ENV: development
      PUBNUB_SUBSCRIBE_KEY: 'sub-c-252ec7e2-7ca4-11e9-89f1-56e8a30b5f0e'
      PUBNUB_PUBLISH_KEY: 'pub-c-5cffb7ac-5697-44e4-bfc4-dcad6bfae55d'
      MESSAGING_TRANSPORT_SERVICE_URL: http://messaging-transport-service:9840
      SERVER_PORT: 9836
      DATABASE_CONNECTION_URL: 'postgresql://user_messaging:e5YGE3cQ2ysqHesT@postgres:5432/test_messaging'
      PUBNUB_SUBSCRIBE_KEY: 'sub-c-252ec7e2-7ca4-11e9-89f1-56e8a30b5f0e'
      PUBNUB_PUBLISH_KEY: 'pub-c-937068cd-2e67-4c0e-a1eb-3c108d85f9e7'
      AWS_CLOUDFRONT_ACCESS_KEY_ID: 'aws-id'
      AWS_CLOUDFRONT_PRIVATE_KEY: 'aws-private-key'
      DEFAULT_CLIENT_ID: '4cf2c57b-ab68-4415-9b1d-9876df5d307f'
      AWS_CLOUDFRONT_DOMAIN: 'http://my.cloudfront.com/'
      AWS_REGION: 'eu-west-1'
      DISABLE_DDTRACE: 1
      SQS_ENDPOINT: 'http://localstack:4566'
      SNS_ENDPOINT: 'http://localstack:4566'
      DEEPLINK_BASE_URL: 'https://link.dev.global.id'
      AWS_CHIME_SERVICE_URL: 'https://service.chime.aws.amazon.com/console'
      AWS_CHIME_KEY_ID: 'aws_chime_key_id'
      AWS_CHIME_SECRET_KEY: 'aws_chime_secret_key'
      AWS_ACCESS_KEY_ID: invalid
      AWS_SECRET_ACCESS_KEY: invalid
      JWT_PUBLIC_KEY: 'sigsecret'
      JWT_ISSUER: 'https://iss.uer'
      SVC_URL_CONTACTS: 'http://contacts:8080'
      SVC_URL_GROUP: 'http://group-service:9125'
      SVC_URL_IDENTITY_NAMESPACE: 'http://identity-namespace-service:9992'
      SVC_URL_KEYSTORE: 'http://keystore-service:9123'
      SVC_URL_UPLOAD: 'http://upload:8080'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379

  cockroach_node_1:
    container_name: cockroach_node_1
    image: cockroachdb/cockroach:latest
    volumes:
      - ./data/node_1:/cockroach/cockroach-data
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      cockroachdb_net:
        aliases:
          - cockroach_node_1

  cockroach_node_2:
    container_name: cockroach_node_2
    image: cockroachdb/cockroach:latest
    volumes:
      - ./data/node_2:/cockroach/cockroach-data
    command: start --insecure --join=cockroach_node_1
    networks:
      cockroachdb_net:
        aliases:
          - cockroach_node_2

networks:
  cockroachdb_net:
    driver: bridge
