version: '3.7'

volumes:
  postgres:

services:
  #postgres:
  #  image: postgres:12
  #  restart: always
  #  environment:
  #    - POSTGRES_DB=${DOCKER_DATABASE_NAME}
  #    - POSTGRES_USER=${DOCKER_DATABASE_USERNAME}
  #    - POSTGRES_PASSWORD=${DOCKER_DATABASE_PASSWORD}
  #  volumes:
  #    - postgres:/var/lib/postgresql
  #    - postgres:/var/log/postgresql
  #  ports:
  #    - "5432:5432"

  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=${DOCKER_DATABASE_NAME}
      - POSTGRES_USER=${DOCKER_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - postgres:/var/lib/postgresql
      - postgres:/var/log/postgresql
      - ./pg-init-scripts:/docker-entrypoint-initdb.d

  localstack:
    container_name: localstack_repo
    volumes:
      - '/tmp/localstack'
    image: localstack/localstack-light:0.14.0
    ports:
      # - '4569:4569' # dynamo
      # - '4571:4571' # elastic
      - '4572:4572' # s3
      # - '4575:4575' # sns
      # - '4576:4576' # sqs
      # - '4579:4579' # ses
      # - '8888:8888' # web interface
      - '4566:4566'   # all
    environment:
      - PORT_WEB_UI=8080
      - SERVICES=sqs,sns,s3,ses
      - DEBUG=1
      - AWS_BUCKET='gid-dev-openapi-documentation'

  redis:
    image: redislabs/redisearch
    ports:
      - '6378:6379'
